// <auto-generated />
namespace InitiativeManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_initiative : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_initiative));
        
        string IMigrationMetadata.Id
        {
            get { return "201801281657246_update_initiative"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
